title: Elias "Eliyahu" Suskind
email: eliassuskind@yahoo.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my Portfolio Website!
baseurl: "" # the subpath of your site, e.g. /blog
url: https://JakobFinci.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  JakobFinci

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "neon"

markdown: "kramdown"

header:
  show_overlay_excerpt: false

plugins:
  - jekyll-feed

atom_feed:
  hide: true

defaults:
  - values:
      layout: single

include:
  - _pages